### PR TITLE
a few perf improvements

### PR DESCRIPTION
**Pull request by pelikhan**
Baseline 1.2.3: rock paper scissors, 9.5fps, 5.4fps with led editor
- drop shadow on tiles: 2fps
- drop bounds checking on all sprites: 2fps

### CODE REVIEW

**Comment by pelikhan** [comment]
rps: 14.6fps
leds: 7.2fps

**Comment by pelikhan** [comment]
rps: 15.9fps
leds: 8.9fps

**Review by eanders-ms — APPROVED** [review]
nice

**Comment by pelikhan** [comment]
rps: 16.7fps
leds: 8fps

**Pull request merged**
