### PR TITLE
Picker selection

### PR DESCRIPTION
**Pull request by ramseyball**

### CODE REVIEW

**Comment by ramseyball** [comment]
@pelikhan - when bringing up a menu on an existing tile, this change will show which option in menu was selected

**Comment by ramseyball** [comment]
Oops. Not quite ready

**Comment by pelikhan** [comment]
That's a lot of change, will wait till your are back.

**Comment by ramseyball** [comment]
Small change actually, i just separated ruleeditor into a different file, editor was getting too large

**Comment by ramseyball** [comment]
Try it out. If it works, please merge.

**Comment by pelikhan** [comment]
Not working for me, it still goes on the first item.

**Comment by ramseyball** [comment]
Thanks for trying…

**Pull request merged**
